image: gitpod/workspace-full

tasks:
  - init: |
      sudo apt update && sudo apt install -y openjdk-17-jdk android-sdk
      git config --global user.name "Smike10"
      git config --global user.email "tu-correo@gmail.com"

ports:
  - port: 8080
    onOpen: open-browser
